export const MOCK_APIS = [
    {
        id: "openai-gpt4",
        name: "OpenAI GPT-4",
        description: "The most advanced AI model for natural language processing, code generation, and reasoning.",
        category: "AI & NLP",
        rating: 4.9,
        pricing: "Paid",
        confidenceScore: 99,
    },
    {
        id: "spotify-web-api",
        name: "Spotify Web API",
        description: "Access music data, playlists, and user playback control directly from your application.",
        category: "Music & Audio",
        rating: 4.8,
        pricing: "Free",
        confidenceScore: 98,
    },
    {
        id: "auth0",
        name: "Auth0",
        description: "Secure access for everyone. But not just anyone. Authentication and authorization as a service.",
        category: "Authentication",
        rating: 4.7,
        pricing: "Freemium",
        confidenceScore: 99,
    },
    {
        id: "openweathermap",
        name: "OpenWeatherMap",
        description: "Access current weather data for any location on Earth including over 200,000 cities.",
        category: "Weather",
        rating: 4.6,
        pricing: "Freemium",
        confidenceScore: 95,
    },
    {
        id: "stripe-api",
        name: "Stripe API",
        description: "The standard for online payments. Accept payments, send payouts, and manage your business online.",
        category: "Crypto & Finance",
        rating: 4.9,
        pricing: "Paid",
        confidenceScore: 99,
    },
    {
        id: "google-maps-platform",
        name: "Google Maps",
        description: "Customize maps with your own content and imagery. Build with the world's most trusted map data.",
        category: "Maps",
        rating: 4.8,
        pricing: "Paid",
        confidenceScore: 99,
    },
    {
        id: "twitter-api-v2",
        name: "X (Twitter) API",
        description: "Access the public conversation. Retrieve tweets, users, and trends programmatically.",
        category: "Social Media",
        rating: 3.5,
        pricing: "Paid",
        confidenceScore: 85,
    },
    {
        id: "twilio-api",
        name: "Twilio",
        description: "Connect with customers on their preferred channels—anywhere in the world.",
        category: "Communication",
        rating: 4.7,
        pricing: "Paid",
        confidenceScore: 98,
    },
    {
        id: "skyscanner-api",
        name: "Skyscanner",
        description: "Flight search API for travel applications. Get live pricing and availability.",
        category: "Travel",
        rating: 4.5,
        pricing: "Free",
        confidenceScore: 92,
    },
    {
        id: "coingecko-api",
        name: "CoinGecko",
        description: "The world's most comprehensive cryptocurrency data API. Prices, market cap, and more.",
        category: "Crypto & Finance",
        rating: 4.8,
        pricing: "Freemium",
        confidenceScore: 96,
    },
    {
        id: "clarifai",
        name: "Clarifai",
        description: "Computer vision, NLP, and audio recognition API for developers and data scientists.",
        category: "Computer Vision",
        rating: 4.4,
        pricing: "Freemium",
        confidenceScore: 90,
    },
    {
        id: "cricket-data-api",
        name: "Cricket Data",
        description: "Live cricket scores, player stats, and historical data for cricket matches worldwide.",
        category: "Sports",
        rating: 4.2,
        pricing: "Paid",
        confidenceScore: 88,
    },
] as const;
